[package]
name = "substrate-test-runtime-transaction-pool"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "substrate-test-runtime-transaction-pool (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
thiserror = { workspace = true }
sc-transaction-pool = { path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { path = "../../../client/transaction-pool/api" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-runtime = { path = "../../../primitives/runtime" }
substrate-test-runtime-client = { path = "../client" }
log = "0.4.20"